/** P37I-C5: newly authored contextual prompts, not part of the P35 source corpus.
 * These are independent communicative situations. Deterministic matching can
 * certify only an exact model sentence, never full semantic correctness.
 * Keep learner text out of persistence and exports.
 */
export interface ContextScene{
  id:string;recordId:string;variant:0|1;
  situation:string;english:string;expected:string;
  hint:string;
}
export const CONTEXT_SCENES:readonly ContextScene[]=[
  {id:'c5-001a',recordId:'p10-001',variant:0,situation:'Language class',
    english:'I am learning to read in French.',expected:"J'apprends à lire en français.",
    hint:'Use apprendre à + infinitive with je.'},
  {id:'c5-001b',recordId:'p10-001',variant:1,situation:'Home',
    english:'She is learning to cook.',expected:'Elle apprend à cuisiner.',
    hint:'Use apprendre à + infinitive with elle.'},
  {id:'c5-004a',recordId:'p10-004',variant:0,situation:'Family',
    english:'I help my sister to study.',expected:"J'aide ma sœur à étudier.",
    hint:'Use aider + person + à + infinitive.'},
  {id:'c5-004b',recordId:'p10-004',variant:1,situation:'Neighborhood',
    english:'We help our neighbor carry the bags.',expected:'Nous aidons notre voisin à porter les sacs.',
    hint:'Use aider + person + à + infinitive.'},
  {id:'c5-013a',recordId:'p10-013',variant:0,situation:'Planning',
    english:'I decided to study tonight.',expected:"J'ai décidé d'étudier ce soir.",
    hint:'Use décider de + infinitive in the passé composé.'},
  {id:'c5-013b',recordId:'p10-013',variant:1,situation:'Travel',
    english:'We decided to leave early.',expected:'Nous avons décidé de partir tôt.',
    hint:'Use décider de + infinitive in the passé composé.'},
  {id:'c5-023a',recordId:'p10-023',variant:0,situation:'Family',
    english:'I ask my brother to wait.',expected:"Je demande à mon frère d'attendre.",
    hint:'Use demander à + person + de + infinitive.'},
  {id:'c5-023b',recordId:'p10-023',variant:1,situation:'Work',
    english:'She asks her colleague to call tomorrow.',expected:"Elle demande à son collègue d'appeler demain.",
    hint:'Use demander à + person + de + infinitive.'},
  {id:'c5-036a',recordId:'p10-036',variant:0,situation:'Weather',
    english:'We must take the weather into account.',expected:'Nous devons tenir compte de la météo.',
    hint:'Use tenir compte de + noun.'},
  {id:'c5-036b',recordId:'p10-036',variant:1,situation:'Classroom',
    english:'The teacher takes our questions into account.',expected:'Le professeur tient compte de nos questions.',
    hint:'Conjugate tenir in the present, then use compte de.'},
  {id:'c5-048a',recordId:'p10-048',variant:0,situation:'Studying',
    english:'I have trouble understanding this word.',expected:"J'ai du mal à comprendre ce mot.",
    hint:'Use avoir du mal à + infinitive.'},
  {id:'c5-048b',recordId:'p10-048',variant:1,situation:'Travel',
    english:'They have trouble finding the station.',expected:'Ils ont du mal à trouver la gare.',
    hint:'Use avoir du mal à + infinitive.'},
  {id:'c5-050a',recordId:'p10-050',variant:0,situation:'University',
    english:'I take notes during class.',expected:'Je prends des notes pendant le cours.',
    hint:'Conjugate prendre; use des notes.'},
  {id:'c5-050b',recordId:'p10-050',variant:1,situation:'Work',
    english:'We take notes during the meeting.',expected:'Nous prenons des notes pendant la réunion.',
    hint:'Conjugate prendre with nous.'},
  {id:'c5-065a',recordId:'p10-065',variant:0,situation:'Healthcare',
    english:'I made an appointment with the doctor.',expected:"J'ai pris rendez-vous avec le médecin.",
    hint:'Use prendre rendez-vous avec in the passé composé.'},
  {id:'c5-065b',recordId:'p10-065',variant:1,situation:'Dental clinic',
    english:'She is making an appointment with the dentist.',expected:'Elle prend rendez-vous avec le dentiste.',
    hint:'Use prendre rendez-vous avec in the present.'},
  {id:'c6-002a',recordId:'p10-002',variant:0,situation:'At home',
    english:'I manage to open the window.',expected:"J'arrive à ouvrir la fenêtre.",
    hint:'Use arriver à + infinitive with je.'},
  {id:'c6-002b',recordId:'p10-002',variant:1,situation:'In class',
    english:'She manages to understand the explanation.',expected:'Elle arrive à comprendre l’explication.',
    hint:'Use arriver à + infinitive with elle.'},
  {id:'c6-014a',recordId:'p10-014',variant:0,situation:'Mathematics',
    english:'I am trying to solve the problem.',expected:"J'essaie de résoudre le problème.",
    hint:'Use essayer de + infinitive with je.'},
  {id:'c6-014b',recordId:'p10-014',variant:1,situation:'Community',
    english:'We are trying to help our neighbors.',expected:"Nous essayons d'aider nos voisins.",
    hint:'Use essayer de + infinitive with nous.'},
  {id:'c6-018a',recordId:'p10-018',variant:0,situation:'Family',
    english:'I promise to come back tomorrow.',expected:'Je promets de revenir demain.',
    hint:'Use promettre de + infinitive with je.'},
  {id:'c6-018b',recordId:'p10-018',variant:1,situation:'Work',
    english:'They promise to finish on time.',expected:'Ils promettent de finir à temps.',
    hint:'Use promettre de + infinitive with ils.'},
  {id:'c6-051a',recordId:'p10-051',variant:0,situation:'At the office',
    english:'I take note of your address.',expected:'Je prends note de votre adresse.',
    hint:'Use prendre note de + noun.'},
  {id:'c6-051b',recordId:'p10-051',variant:1,situation:'Planning meeting',
    english:'We take note of this suggestion.',expected:'Nous prenons note de cette suggestion.',
    hint:'Use prendre note de + noun.'},

  // C5B: 24 additional high-frequency constructions, each with two genuinely
  // different tasks. These are authored learning examples, not P35 quotations.
  {id:'c5b-003a',recordId:'p10-003',variant:0,situation:'Self-study',
    english:'I am trying to improve my French.',expected:"Je cherche à améliorer mon français.",
    hint:'Use chercher à with je and the infinitive améliorer.'},
  {id:'c5b-003b',recordId:'p10-003',variant:1,situation:'Company planning',
    english:'The team is trying to reduce costs.',expected:"L'équipe cherche à réduire les coûts.",
    hint:'Use chercher à with a singular team.'},
  {id:'c5b-005a',recordId:'p10-005',variant:0,situation:'Family encouragement',
    english:'I encourage my brother to continue.',expected:"J'encourage mon frère à continuer.",
    hint:'Use encourager + person + à + infinitive.'},
  {id:'c5b-005b',recordId:'p10-005',variant:1,situation:'Classroom discussion',
    english:'The teacher encourages the students to ask questions.',expected:"Le professeur encourage les élèves à poser des questions.",
    hint:'Use encourager followed by the students and à poser.'},
  {id:'c5b-006a',recordId:'p10-006',variant:0,situation:'Lunch invitation',
    english:'I invite my colleague to lunch.',expected:"J'invite ma collègue à déjeuner.",
    hint:'Use inviter + person + à + infinitive.'},
  {id:'c5b-006b',recordId:'p10-006',variant:1,situation:'Community gathering',
    english:'We invite our friends to join us.',expected:"Nous invitons nos amis à nous rejoindre.",
    hint:'Use inviter with nous and an infinitive after à.'},
  {id:'c5b-007a',recordId:'p10-007',variant:0,situation:'Holiday planning',
    english:'I am thinking of booking the tickets.',expected:"Je pense à réserver les billets.",
    hint:'Use penser à + infinitive.'},
  {id:'c5b-007b',recordId:'p10-007',variant:1,situation:'Family check-in',
    english:'She thinks of calling her grandmother.',expected:"Elle pense à appeler sa grand-mère.",
    hint:'Use penser à with elle; recall the person to call.'},
  {id:'c5b-012a',recordId:'p10-012',variant:0,situation:'Health',
    english:'He stops smoking.',expected:"Il arrête de fumer.",
    hint:'Use arrêter de + infinitive.'},
  {id:'c5b-012b',recordId:'p10-012',variant:1,situation:'Work schedule',
    english:'We stop working at six o’clock.',expected:"Nous arrêtons de travailler à six heures.",
    hint:'Use arrêter de with nous and the work infinitive.'},
  {id:'c5b-015a',recordId:'p10-015',variant:0,situation:'Reading',
    english:'I have finished reading the book.',expected:"J'ai fini de lire le livre.",
    hint:'Use finir de + infinitive in the passé composé.'},
  {id:'c5b-015b',recordId:'p10-015',variant:1,situation:'Cooking',
    english:'They are finishing preparing dinner.',expected:"Ils finissent de préparer le dîner.",
    hint:'Use finir de with ils and préparer.'},
  {id:'c5b-016a',recordId:'p10-016',variant:0,situation:'Leaving home',
    english:'I forgot to close the window.',expected:"J'ai oublié de fermer la fenêtre.",
    hint:'Use oublier de + infinitive in the passé composé.'},
  {id:'c5b-016b',recordId:'p10-016',variant:1,situation:'Weather preparation',
    english:'She forgets to take her umbrella.',expected:"Elle oublie de prendre son parapluie.",
    hint:'Use oublier de in the present with elle.'},
  {id:'c5b-017a',recordId:'p10-017',variant:0,situation:'Public transport',
    english:'This pass allows my friend to travel for free.',expected:"Cette carte permet à mon ami de voyager gratuitement.",
    hint:'Use permettre à + person + de + infinitive.'},
  {id:'c5b-017b',recordId:'p10-017',variant:1,situation:'School software',
    english:'This software allows students to share their notes.',expected:"Ce logiciel permet aux étudiants de partager leurs notes.",
    hint:'Use permettre aux étudiants de partager.'},
  {id:'c5b-019a',recordId:'p10-019',variant:0,situation:'Team meeting',
    english:'I suggest starting earlier.',expected:"Je propose de commencer plus tôt.",
    hint:'Use proposer de + infinitive.'},
  {id:'c5b-019b',recordId:'p10-019',variant:1,situation:'Event planning',
    english:'She suggests organizing a meeting.',expected:"Elle propose d'organiser une réunion.",
    hint:'Use proposer de with the elided form d’organiser.'},
  {id:'c5b-020a',recordId:'p10-020',variant:0,situation:'Interview',
    english:'He refuses to answer the question.',expected:"Il refuse de répondre à la question.",
    hint:'Use refuser de + infinitive.'},
  {id:'c5b-020b',recordId:'p10-020',variant:1,situation:'Price negotiation',
    english:'We refuse to pay more.',expected:"Nous refusons de payer plus.",
    hint:'Use refuser de with nous.'},
  {id:'c5b-021a',recordId:'p10-021',variant:0,situation:'Travel aspiration',
    english:'I dream of visiting Japan.',expected:"Je rêve de visiter le Japon.",
    hint:'Use rêver de + infinitive.'},
  {id:'c5b-021b',recordId:'p10-021',variant:1,situation:'Future home',
    english:'They dream of living near the sea.',expected:"Ils rêvent de vivre près de la mer.",
    hint:'Use rêver de with ils.'},
  {id:'c5b-022a',recordId:'p10-022',variant:0,situation:'Helping a friend',
    english:'I agree to help you tonight.',expected:"J'accepte de t'aider ce soir.",
    hint:'Use accepter de + infinitive, with t’aider.'},
  {id:'c5b-022b',recordId:'p10-022',variant:1,situation:'Work schedule',
    english:'She agrees to change her schedule.',expected:"Elle accepte de changer son horaire.",
    hint:'Use accepter de followed by changer.'},
  {id:'c5b-029a',recordId:'p10-029',variant:0,situation:'Homework',
    english:'I explain the problem to my sister.',expected:"J'explique le problème à ma sœur.",
    hint:'Use expliquer + thing + à + person.'},
  {id:'c5b-029b',recordId:'p10-029',variant:1,situation:'City tour',
    english:'The guide explains the route to the visitors.',expected:"Le guide explique le trajet aux visiteurs.",
    hint:'Use expliquer and the contraction aux.'},
  {id:'c5b-030a',recordId:'p10-030',variant:0,situation:'Sharing memories',
    english:'I show my photos to my friend.',expected:"Je montre mes photos à mon ami.",
    hint:'Use montrer + thing + à + person.'},
  {id:'c5b-030b',recordId:'p10-030',variant:1,situation:'Tourist information',
    english:'She shows the map to the tourists.',expected:"Elle montre la carte aux touristes.",
    hint:'Use montrer and the contraction aux.'},
  {id:'c5b-032a',recordId:'p10-032',variant:0,situation:'Staircase',
    english:'Watch out for the step.',expected:"Fais attention à la marche.",
    hint:'Use faire attention à + noun in the tu imperative.'},
  {id:'c5b-032b',recordId:'p10-032',variant:1,situation:'Crossing a street',
    english:'We pay attention to the cars.',expected:"Nous faisons attention aux voitures.",
    hint:'Use faire attention à and the contraction aux.'},
  {id:'c5b-039a',recordId:'p10-039',variant:0,situation:'After exercising',
    english:'I am hungry after exercising.',expected:"J'ai faim après le sport.",
    hint:'Use avoir faim, not être faim.'},
  {id:'c5b-039b',recordId:'p10-039',variant:1,situation:'Family dinner',
    english:'The children are hungry before dinner.',expected:"Les enfants ont faim avant le dîner.",
    hint:'Use avoir faim with a plural subject.'},
  {id:'c5b-040a',recordId:'p10-040',variant:0,situation:'After running',
    english:'I am thirsty after the run.',expected:"J'ai soif après la course.",
    hint:'Use avoir soif.'},
  {id:'c5b-040b',recordId:'p10-040',variant:1,situation:'Hiking',
    english:'We are thirsty during the hike.',expected:"Nous avons soif pendant la randonnée.",
    hint:'Use avoir soif with nous.'},
  {id:'c5b-043a',recordId:'p10-043',variant:0,situation:'Public speaking',
    english:'I am afraid to speak in public.',expected:"J'ai peur de parler en public.",
    hint:'Use avoir peur de + infinitive.'},
  {id:'c5b-043b',recordId:'p10-043',variant:1,situation:'Meeting animals',
    english:'She is afraid of dogs.',expected:"Elle a peur des chiens.",
    hint:'Use avoir peur de + plural noun and its contraction.'},
  {id:'c5b-044a',recordId:'p10-044',variant:0,situation:'Bedtime',
    english:'I feel like sleeping.',expected:"J'ai envie de dormir.",
    hint:'Use avoir envie de + infinitive.'},
  {id:'c5b-044b',recordId:'p10-044',variant:1,situation:'Weekend plans',
    english:'We feel like going out tonight.',expected:"Nous avons envie de sortir ce soir.",
    hint:'Use avoir envie de with nous.'},
  {id:'c5b-045a',recordId:'p10-045',variant:0,situation:'Writing homework',
    english:'I need a pen.',expected:"J'ai besoin d'un stylo.",
    hint:'Use avoir besoin de + noun, elided before un.'},
  {id:'c5b-045b',recordId:'p10-045',variant:1,situation:'Project deadline',
    english:'They need more time.',expected:"Ils ont besoin de plus de temps.",
    hint:'Use avoir besoin de with ils.'},
  {id:'c5b-049a',recordId:'p10-049',variant:0,situation:'Project planning',
    english:'We must make a decision today.',expected:"Nous devons prendre une décision aujourd'hui.",
    hint:'Use prendre une décision.'},
  {id:'c5b-049b',recordId:'p10-049',variant:1,situation:'Personal change',
    english:'She made a difficult decision.',expected:"Elle a pris une décision difficile.",
    hint:'Use prendre une décision in the passé composé.'},
  {id:'c5b-052a',recordId:'p10-052',variant:0,situation:'Language learning',
    english:'I make an effort to speak French.',expected:"Je fais un effort pour parler français.",
    hint:'Use faire un effort and pour + infinitive.'},
  {id:'c5b-052b',recordId:'p10-052',variant:1,situation:'Arriving punctually',
    english:'They made an effort to arrive on time.',expected:"Ils ont fait un effort pour arriver à l'heure.",
    hint:'Use faire un effort in the passé composé.'},
  {id:'c5b-053a',recordId:'p10-053',variant:0,situation:'French study',
    english:'I am making progress in French.',expected:"Je fais des progrès en français.",
    hint:'Use faire des progrès.'},
  {id:'c5b-053b',recordId:'p10-053',variant:1,situation:'Swimming lessons',
    english:'She has made progress in swimming.',expected:"Elle a fait des progrès en natation.",
    hint:'Use faire des progrès in the passé composé.'},
  {id:'c5b-055a',recordId:'p10-055',variant:0,situation:'Weekend chores',
    english:'I do the cleaning on Saturdays.',expected:"Je fais le ménage le samedi.",
    hint:'Use faire le ménage with je.'},
  {id:'c5b-055b',recordId:'p10-055',variant:1,situation:'Preparing for a party',
    english:'We did the cleaning before the party.',expected:"Nous avons fait le ménage avant la fête.",
    hint:'Use faire le ménage in the passé composé.'},
];
const sceneMap=new Map(CONTEXT_SCENES.map(scene=>[scene.recordId+':'+scene.variant,scene]));
export function contextScene(recordId:string,variant:0|1):ContextScene|undefined{
  return sceneMap.get(recordId+':'+variant);
}
export function hasContextScenes(recordId:string):boolean{
  return Boolean(contextScene(recordId,0)&&contextScene(recordId,1));
}
function canonical(text:string):string{
  return text.toLocaleLowerCase('fr').normalize('NFC').replace(/’/g,"'")
    .replace(/\s+([,.;!?])/g,'$1').replace(/\s+/g,' ').trim();
}
function withoutAccents(text:string):string{
  return canonical(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'');
}
export type ContextAssessment='exact'|'orthography'|'needs-human-review'|'blank';
export function assessContextAnswer(text:string,scene:ContextScene):ContextAssessment{
  if(!text.trim())return 'blank';
  if(canonical(text)===canonical(scene.expected))return 'exact';
  if(withoutAccents(text)===withoutAccents(scene.expected))return 'orthography';
  return 'needs-human-review';
}
